name: Hello World!

on:
  push:
    branches:
      - secondary
env:
    COMMITS: ${{ (github.event.commits) }}
    CONDITION: ${{ conntains("$COMMITS", 'skip') }}
jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    if: ${{ github.env.CONDITION == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        run: echo "something"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
