name: Deployment pipeline

on:
  push:
    branches:
      - main
      - secondary
  pull_request:
    branches: [main, master]
    types: 
      - opened 
      - synchronize 
      - closed
env:
    CONDITION: ${{ contains(github.event.commits, 'skip') }}

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run playWright test
        run: npx playwright install --with-deps && npm run test:e2e
  
  notify:
    needs: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Test webook Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  deploy:
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'skip')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: 'Change ownership build file'
        run: chmod -v +x build_step.sh
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API }}
          wait-for-success: true
  
  versioning:
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  && !contains(github.event.head_commit.message, 'skip')
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} # if you don't want to set write permissions use a PAT token
        DEFAULT_BUMP: 'patch'
        WITH_V: true
        PRERELEASE: true
    
  


